### ISSUE TITLE
2 questions/issues

### ISSUE THREAD

**Issue by deibraz-free** [ok24601/etoro-api#18]
Firslty, amazing work.

So, onward with questions:
* Does this scrape data already being sent by etoro or does it fetch data on its own every second or so?
* Is there a way to get info about currently open positions?

**Comment by oleh2208** [comment]
Hi,
1. i‘m using websocket server from etoro and geting price and positions data from there
2. Try get open positions request

**Comment by freemmaann** [comment]
I've talked to etoro staff. These things are a ban-able offense, sadly.

**Comment by oleh2208** [comment]
Ok good to know
