### ISSUE TITLE
way to output data on current positions to python

### ISSUE THREAD

**Issue by MaxWvM** [ok24601/etoro-api#37]
I was wondering if there was a way to send the data of current open positions to python so i can run my own market analysis.

**Comment by MaxWvM** [comment]
more specific, i'd like to get the proffit and w/v rate of all current open trades, and then output the transaction id, so i can run that past the close position in the api when certain conditions are met.

**Comment by ok24601** [comment]
hi,

you could try getPositions endpoint, it return list of the open possitions in such format:
  [ {
        "instrumentID": "100000",
        "isBuy": true,
        "openRate": 23971.84,
        "leverage": 1,
        "amount": 100.0,
        "stopLossRate": 0.01,
        "takeProfitRate": 0.0,
        "positionID": "126951406",
        "isTslEnabled": false,
        "view_MaxPositionUnits": 0,
        "view_Units": 0.0,
        "view_openByUnits": null,
        "viewRateContext": null,
        "openDateTime": "2020-12-23T13:18:22.45Z",
        "isDiscounted": false,
        "closeRate": null,
        "netProfit": 124.61951189395558,
        "closeDateTime": null
    }
]

best regards,
Oleg


________________________________
От: MaxWvM <notifications@github.com>
Отправлено: 8 марта 2021 г. 11:15
Кому: ok24601/etoro-api <etoro-api@noreply.github.com>
Копия: Subscribed <subscribed@noreply.github.com>
Тема: Re: [ok24601/etoro-api] way to output data on current positions to python (#37)


more specific, i'd like to get the proffit and w/v rate of all current open trades, and then output the transaction id, so i can run that past the close position in the api when certain conditions are met.
